name: Reply Issue

on:
  issue_comment:
    types: [created, edited]

jobs:
  reply_issue:
    name: Reply Issue
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:      
      - name: Reply Comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you ${{ github.event.issue.user.login }} for updating and replying this issue
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]
          reactions: heart