name: Issues

on:
  issues:
    types:
      - opened

jobs:
  label_issue:
    name: Label Issue
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: peter-evans/create-or-update-comment@v2
      - name: Print Gihthub events
        run: |
          echo issue number ${{ github.event.pull_request.number }}
