name: Issues

on:
  issues:
    types:
      - opened

jobs:
  label_issue:
    name: Label Issue
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Print Gihthub events
        run: |
          echo ${{ github.event }}
