name: Issues

on:
  issues:
    types:
      - opened

jobs:
  label_issue:
    name: Label Issue
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: 1
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
      - name: Print Gihthub events
        run: |
          echo issue number ${{ github.event.pull_request.number }}
