name: Issues

on:
  issues:
    types:
      - opened

jobs:
  comment_issue:
    name: Comment Issue
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you ${{ github.event.issue.user.login }} for filing this issue
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: heart
      - name: Print Gihthub events
        run: echo "GITHUB CONTEXT ${{ toJSON(github) }}"
        shell: bash
