name: Linters

on:
  [push]

jobs:
  eslint:
    name: Eslint
    runs-on: ubuntu-18.04
    steps:
      - name: Pre Actions
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Hello world
        run: echo Greeting world
        
