name: Linters

on:
  [push]

jobs:
  eslint:
    name: Eslint
    strategy:
      matrix:
        version: [10, 12]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Default Pre Actions
        uses: actions/checkout@v2
      - name: Use Nodejs
        uses: actions/setup-node@v1
      - name: Echo matrix name
        run: echo Matrix OS ${{ matrix.os }}
