name: Linters

on:
  [push]

jobs:
  eslint:
    name: Eslint
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Use Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup ESLint
        run: |
          npm install --save-dev @vue/cli-plugin-babel@4.5.0 @vue/cli-plugin-eslint@4.5.0 babel-eslint@10.1.0 eslint@6.7.2 eslint-plugin-vue@7.0.0 @vue/cli-service@4.5.0 @vue/compiler-sfc@3.0.0
          [ -f .eslintrc.js ]
      - name: ESLint Report
        run: npm run lint
