name: Linters

on:
  [push]

jobs:
  eslint:
    name: Eslint
    runs-on: ubuntu-latest
    steps:
      - name: Default Pre Actions
        uses: actions/checkout@v2
      - name: Use Nodejs
        uses: actions/setup-node@v1
      - name: Hello world
        run: echo Greeting world
